"""add identity fields to attendance records

Revision ID: 8b6f65990576
Revises: b831c6cb3ef7
Create Date: 2025-12-08 08:29:25.365937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6f65990576'
down_revision: Union[str, Sequence[str], None] = 'b831c6cb3ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('method', sa.String(), nullable=True))
    op.add_column('attendance_records', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('attendance_records', sa.Column('student_number', sa.String(), nullable=True))
    op.add_column('attendance_records', sa.Column('actor_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_records', 'actor_role')
    op.drop_column('attendance_records', 'student_number')
    op.drop_column('attendance_records', 'full_name')
    op.drop_column('attendance_records', 'method')
    # ### end Alembic commands ###
